export const data = {
  users: [
    {
      username: "user1",
      fullName: "User One",
      email: "user1@example.com",
      password: "password1",
      followers: [],
      profileImage: "image1.jpg",
      coverImage: "cover1.jpg",
    },
    {
      username: "user2",
      fullName: "User Two",
      email: "user2@example.com",
      password: "password2",
      followers: [{ user_id: "user1" }],
      profileImage: "image2.jpg",
      coverImage: "cover2.jpg",
    },
    {
      username: "user3",
      fullName: "User Three",
      email: "user3@example.com",
      password: "password3",
      followers: [],
      profileImage: "image3.jpg",
      coverImage: "cover3.jpg",
    },
    {
      username: "user4",
      fullName: "User Four",
      email: "user4@example.com",
      password: "password4",
      followers: [{ user_id: "user2" }, { user_id: "user3" }],
      profileImage: "image4.jpg",
      coverImage: "cover4.jpg",
    },
    {
      username: "user5",
      fullName: "User Five",
      email: "user5@example.com",
      password: "password5",
      followers: [{ user_id: "user1" }, { user_id: "user4" }],
      profileImage: "image5.jpg",
      coverImage: "cover5.jpg",
    },
    {
      username: "user6",
      fullName: "User Six",
      email: "user6@example.com",
      password: "password6",
      followers: [],
      profileImage: "image6.jpg",
      coverImage: "cover6.jpg",
    },
    {
      username: "user7",
      fullName: "User Seven",
      email: "user7@example.com",
      password: "password7",
      followers: [{ user_id: "user5" }],
      profileImage: "image7.jpg",
      coverImage: "cover7.jpg",
    },
    {
      username: "user8",
      fullName: "User Eight",
      email: "user8@example.com",
      password: "password8",
      followers: [{ user_id: "user6" }],
      profileImage: "image8.jpg",
      coverImage: "cover8.jpg",
    },
    {
      username: "user9",
      fullName: "User Nine",
      email: "user9@example.com",
      password: "password9",
      followers: [{ user_id: "user7" }, { user_id: "user8" }],
      profileImage: "image9.jpg",
      coverImage: "cover9.jpg",
    },
    {
      username: "user10",
      fullName: "User Ten",
      email: "user10@example.com",
      password: "password10",
      followers: [{ user_id: "user3" }],
      profileImage: "image10.jpg",
      coverImage: "cover10.jpg",
    },
  ],
  posts: [
    {
      title: "Exploring the Wilderness",
      description:
        "Hiking through lush forests and discovering hidden waterfalls.",
      images: ["wilderness_image1.jpg", "wilderness_image2.jpg"],
      likes: [{ user_id: "user1" }, { user_id: "user3" }],
      dislikes: [],
      comments: [
        {
          comment: "This looks like an amazing adventure!",
          user_id: "user2",
          post_id: "post1",
          likes: 5,
          dislikes: 0,
        },
      ],
    },
    {
      title: "Sunrise at the Beach",
      description: "Starting the day with a serene sunrise by the ocean.",
      images: ["beach_sunrise_image1.jpg"],
      likes: [{ user_id: "user5" }, { user_id: "user7" }],
      dislikes: [{ user_id: "user6" }],
      comments: [],
    },
    {
      title: "City Lights",
      description: "Admiring the vibrant city lights from a rooftop.",
      images: ["city_lights_image1.jpg"],
      likes: [{ user_id: "user4" }],
      dislikes: [],
      comments: [
        {
          comment: "The city never looked better!",
          user_id: "user3",
          post_id: "post3",
          likes: 2,
          dislikes: 0,
        },
      ],
    },
    {
      title: "Delicious Desserts",
      description: "Indulging in a variety of mouthwatering desserts.",
      images: ["desserts_image1.jpg", "desserts_image2.jpg"],
      likes: [],
      dislikes: [],
      comments: [],
    },
    {
      title: "Mountain Retreat",
      description: "Escaping to the mountains for a weekend of tranquility.",
      images: ["mountain_retreat_image1.jpg"],
      likes: [{ user_id: "user2" }, { user_id: "user8" }],
      dislikes: [],
      comments: [],
    },
    {
      title: "Cultural Festival",
      description:
        "Immersing in the vibrant colors and traditions of a local festival.",
      images: ["festival_image1.jpg"],
      likes: [],
      dislikes: [],
      comments: [
        {
          comment: "The cultural diversity is so beautiful!",
          user_id: "user9",
          post_id: "post6",
          likes: 1,
          dislikes: 0,
        },
      ],
    },
    {
      title: "Adventures in the Snow",
      description:
        "Embracing the winter wonderland with snowboarding and skiing.",
      images: ["snow_adventures_image1.jpg", "snow_adventures_image2.jpg"],
      likes: [{ user_id: "user6" }],
      dislikes: [],
      comments: [
        {
          comment: "I wish I was there right now!",
          user_id: "user1",
          post_id: "post7",
          likes: 3,
          dislikes: 0,
        },
      ],
    },
    {
      title: "Serenity by the Lake",
      description: "Finding peace and serenity by a calm lake.",
      images: ["lake_serenity_image1.jpg"],
      likes: [],
      dislikes: [],
      comments: [],
    },
    {
      title: "Artistic Expressions",
      description: "Exploring an art gallery filled with captivating artworks.",
      images: ["art_gallery_image1.jpg"],
      likes: [],
      dislikes: [],
      comments: [],
    },
    {
      title: "Summer Picnic",
      description:
        "Gathering with friends for a delightful summer picnic in the park.",
      images: ["picnic_image1.jpg", "picnic_image2.jpg"],
      likes: [{ user_id: "user7" }],
      dislikes: [],
      comments: [
        {
          comment: "The food looks so delicious!",
          user_id: "user8",
          post_id: "post10",
          likes: 2,
          dislikes: 0,
        },
      ],
    },
  ],
};
